### ISSUE TITLE
Unexpected behavior when using StatesRebuilder with Freezed package

### ISSUE THREAD

**Issue by KhatibFX** [GIfatahTH/states_rebuilder#55] opened 2020-02-25 11:25 UTC
Hello, I am not really sure where to post this issue, so I decided to try here first.

I was trying out the library for my new project, and was following along with the second example:  [https://github.com/GIfatahTH/states_rebuilder/tree/master/examples/002-form_validation_with_reactive_model](url)

I am using the same exact code except I replaced the Email and Password classes by ones using Freezed package: [Freezed package](https://pub.dev/packages/freezed)
Here is my freezed code: 

```dart
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';

part 'freezed_classes.freezed.dart';
part 'freezed_classes.g.dart';

///Email class
@freezed
abstract class Email with _$Email {
  const factory Email(String email) = _Email;
  factory Email.fromJson(Map<String, dynamic> json) => _$EmailFromJson(json);
}

extension EmailExtension on Email {
  void validate() {
    if (email.isEmpty) {
      throw Exception("Email address is required");
    }
  }
}

///Password class
@freezed
abstract class Password with _$Password {
  const factory Password(String password) = _Password;
  factory Password.fromJson(Map<String, dynamic> json) =>
      _$PasswordFromJson(json);
}

extension PasswordExtension on Password {
  void validate() {
    if (password.isEmpty) {
      throw Exception('Password is required');
    }
  }
}
```

Using this code, when I type 'a' for example in the email field, it is good. then if I delete 'a', it gives me the expected error. However, if I type 'a' again, the error persists, even though the validation passes (I debugged with prints). If I type any other character other than the one I just deleted, it works fine. (eg. type 'a', delete 'a', type 'x').

If I use normal classes with the same validation, it works like a charm. Would appreciate if you could help. Thanks!

EDIT: Here is the fulll code for reproduction:

```dart
class LoginPage extends StatelessWidget {
  final ReactiveModel<Email> emailRM = ReactiveModel.create(const Email(''));
  final ReactiveModel<Password> passwordRM =
      ReactiveModel.create(const Password(''));
  bool get isValid => emailRM.hasData && passwordRM.hasData;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Login Page'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListView(
          children: <Widget>[
            //subscribe to emailRM
            StateBuilder(
                models: [emailRM],
                builder: (_, __) {
                  return TextField(
                    onChanged: (String email) {
                      emailRM.setValue(
                        () => Email(email)..validate(),
                        catchError: true,
                      );
                    },
                    keyboardType: TextInputType.emailAddress,
                    decoration: InputDecoration(
                      labelText: "Email Address",
                      errorText: emailRM.error?.message as String,
                    ),
                  );
                }),
            StateBuilder(
                //subscribe to passwordRM
                models: [passwordRM],
                builder: (_, __) {
                  return TextField(
                    onChanged: (String password) {
                      passwordRM.setValue(
                        () => Password(password)..validate(),
                        catchError: true,
                      );
                    },
                    decoration: InputDecoration(
                      labelText: 'Password',
                      errorText: passwordRM.error?.message as String,
                    ),
                    obscureText: true,
                  );
                }),
            StateBuilder(
                //subscribe to both emailRM and passwordRM
                models: [emailRM, passwordRM],
                builder: (_, __) {
                  //this builder is called each time emailRM or passwordRM emit a notification
                  return RaisedButton(
                    onPressed: isValid
                        ? () {
                            Router.navigator
                                .pushReplacementNamed(Router.installationPage);
                          }
                        : null,
                    child: const Text("Submit"),
                  );
                })
          ],
        ),
      ),
    );
  }
}
```

And the normal classes which work fine:

```dart
class Email {
  final String email;

  const Email(this.email);

  void validate() {
    if (email.isEmpty) {
      throw Exception("Email address is required");
    }
  }
}

class Password {
  final String password;

  const Password(this.password);
  void validate() {
    if (password.isEmpty) {
      throw Exception("Password is required");
    }
  }
}

```

**Comment by GIfatahTH** [comment] 2020-02-25 13:11
@KhatibFX  thanks for opening the issue.

In the implementation of `setValue`, if the new value is equal to the last one the rebuild process is stopped.

In both cases: if you type the letter 'a' an instance of `Email ` class is created. If you delete the 'a' and type it again and a new instance of Email class is created.

What makes the difference is the comparison between the last and new instances of email.

In the normal case: the comparison is using the default way so that `Email('a') != Email('a')`. As they are different the rebuild process is triggered.

In the case of `freezed`, the comparison is deep and  Email('a') == Email('a')` which means that the rebuild process is stoped. when you type a different letter  `Email('a') != Email('b') ` and the rebuild process is triggered.

so `Freezed `works as intended, and for states_rebuilder I added to it the ability to take into consideration deep comparison.

Thanks and the issue will be fixed in the next release.

**Closed** 2020-02-26 04:35 UTC
