### ISSUE TITLE
[suggestion/bug] persistantState option to re-invoke builder function 

### ISSUE THREAD

**Issue by samuelstroschein** [GIfatahTH/states_rebuilder#192] opened 2021-05-23 09:49 UTC
### Problem 

PersistantState does not re-invoke the builder function by default and there exists no option to forcefully do so. Without re-invoking the builder function, some use cases like an injected Stream that uses a persistent state are broken. A stream should emit new values and in most cases overwrite the old state. However, if the option of a persistent state is used, the injectedStream returns the persistent state and does not start to listen to the stream itself. Resulting in an outdated state which never updates. 

### Reproducable code
```Dart
import 'package:states_rebuilder/states_rebuilder.dart';
import 'package:test/test.dart';

Injected<DateTime> persistantState = RM.injectStream(
  () => Stream.periodic(Duration(microseconds: 100), (_) => DateTime.now()),
  initialState: DateTime.now(),
  persist: () => PersistState(
    key: 'date',
    toJson: (date) => date.toIso8601String(),
    fromJson: (string) => DateTime.parse(string),
  ),
);

void main() async {
  await RM.storageInitializerMock();
  test('', () async {
    // initializing persistance
    final earlier = persistantState.state;
    await Future.delayed(Duration(milliseconds: 100));
    persistantState.dispose();
    // re-initializing state -> state is loaded from persistence
    final fromPersistantState = persistantState.state;
    await Future.delayed(Duration(milliseconds: 100));
    // now the state should listen to the stream again and the state's datetime
    // should be later
    final shouldBeLater = persistantState.state;
    expect(fromPersistantState.isBefore(shouldBeLater), isTrue);
  });
}
```

**Result**
earlier =                         2021-05-23 11:56:21.014839
fromPersistantState =  2021-05-23 11:56:21.039028
shouldBeLater =           2021-05-23 11:56:21.039028

### Suggestion
Add the `shouldReinvokeBuilderFunction` option to PersistState which is **activated by default in an injectedStream**. 

```Dart
persist: () => PersistState(
    key: 'date',
    shouldReinvokeBuilderFunction: true,
    toJson: (date) => date.toIso8601String(),
    fromJson: (string) => DateTime.parse(string),
  ),
```

**Comment by GIfatahTH** [comment] 2021-05-23 19:01
@samuelstroschein 
In my head when first implemented `persistState`, I had the idea that persisting the state of a stream has no practical use case. But now, form your issue I gess it has.

The logic of state persistence is that once the state is first initialized, it looks for the persisted value and parse it to the state. If there is no persisted value then the creation funtion of the state is invoked to listen to the stream and persist the state.

If the state is already persisted, the creation funtion is never called (the stream never listened to) unless you explicitly refresh the state. This is what happens after dispsoing the state of.

In your test, if you use  `persistantState.refresh() `instead of  `persistantState.dispose()`, the test is passed.

```dart
 test('', () async {
    // initializing persistance
    final earlier = persistantState.state;
    await Future.delayed(Duration(milliseconds: 100));
    persistantState.refresh(); 
    // re-initializing state -> state is loaded from persistence
    final fromPersistantState = persistantState.state;
    await Future.delayed(Duration(milliseconds: 100));
    // now the state should listen to the stream again and the state's datetime
    // should be later
    final shouldBeLater = persistantState.state;
    expect(fromPersistantState.isBefore(shouldBeLater), isTrue);
  });
```

**Comment by samuelstroschein** [comment] 2021-05-24 11:28
@GIfatahTH 
While refreshing the state passes this test, in reality, it is not working because the persistence is "disregarded".  I updated the test to prove why it is not working:

```Dart
import 'package:states_rebuilder/states_rebuilder.dart';
import 'package:test/test.dart';

Injected<DateTime> persistantState = RM.injectStream(
  () => Stream.periodic(Duration(milliseconds: 10), (_) => DateTime.now()),
  initialState: DateTime(1970),
  persist: () => PersistState(
    key: 'date',
    toJson: (date) => date.toIso8601String(),
    fromJson: DateTime.parse,
  ),
);

void main() async {
  await RM.storageInitializerMock();
  test('', () async {
    // initializing persistance
    final initialState = persistantState.state;
    expect(initialState.isAtSameMomentAs(DateTime(1970)), isTrue);
    await Future.delayed(Duration(milliseconds: 100));
    final earlier = persistantState.state;
    expect(earlier.isAfter(initialState), isTrue);
    // explicitly disposing because thats how I do it in the app 
    // probably unnecessary 
    persistantState.dispose();
    // re-initializing state -> state is loaded from persistence
    final fromPersistantState = persistantState.state;
    expect(fromPersistantState.isAtSameMomentAs(earlier), isTrue);

    // explicitly re-invoking the builder function
    persistantState.refresh();
    // but with refresh, the persistence gets lost as the initial state
    // is re-invoked too. 
    expect(persistantState.state.isAtSameMomentAs(initialState), isFalse);

    await Future.delayed(Duration(milliseconds: 100));
    // now the state should listen to the stream again and the state's datetime
    // should be later
    final shouldBeLater = persistantState.state;
    expect(fromPersistantState.isBefore(shouldBeLater), isTrue);
  });
```

```Dart
// this expectation does not hold any longer. 
// In other words, persistence is non-existent as it's disregarded. 
expect(persistantState.state.isAtSameMomentAs(initialState), isFalse);
```

Furthermore, using `refresh` leads to a bug of which I am uncertain if it's caused by states rebuilder or hasura_connect. I assume the state is listened to by a widget which is the first initialization (listening to the stream). If the state is then refreshed by me, the stream is initialized a second time after which Hasura throws an error that the stream already exists. In the networking tab, I do see that two WebSocket streams are opened a millisecond after another. I avoid the issue by forcefully disposing the `streamState` and re-initializing the variable that holds the `streamState` (mutable) on app close. In order to get persistence, I have yet another state `_persistantState` that is consistently set by the `streamState` on data (not dependent on it as I don't want to accidentally invoke listening to the stream). Upon re-initializing the stream variable, I pass the `_persistantState` to the `streamState`.

Regardless of "my" stream issue of which I have not yet found the root cause, persistence with injectedStreams seems broken? My use-case: I am developing an app where data from IoT devices can be seen. I am using the streamed state to show the data in real-time. Persistence is beneficial because upon re-opening the app, the stream needs to be initialized but in the meantime, the previous (persistent) state could be shown in order to avoid loading indicators/missing IoT devices in the UI.

**Comment by GIfatahTH** [comment] 2021-05-24 12:49
@samuelstroschein 
OK, I understand your case. You want to get the stored value (the last state before closing the app) and use it as an initial value of the stream so you can display it while waiting for the stream to get data. This is a good use case.

Am I right?

**Comment by samuelstroschein** [comment] 2021-05-24 18:48
@GIfatahTH exactly! The first value upon re-opening/re-initializing the state should be the persistent value (which is the last value the stream emitted previously).

**Comment by samuelstroschein** [comment] 2021-05-29 09:49
@GIfatahTH I will try the implementation of `shouldRecreateTheState` by the end of next week or the week after next week. (I have to wrap up my bachelor thesis.)

And big sorry that I just saw you already implemented the proposal and merged it because why did you choose `shouldRecreateTheState` as callback? I find it a bit ambiguous since "the state" could refer to the persistent state or the state as created by the creator function.  Something like `shouldReinvokeCreatorFunction` would have been less ambiguous.

**Comment by samuelstroschein** [comment] 2021-06-26 12:06
@GIfatahTH here I am and I found something: 

The implementation works as expected but the state is both has both `isWaiting == true` and `hasData == false` which contradicts the purpose of the implementation because if both values are true and false respectively, developers will show a LoadingSpinner. I would probably leave `isWaiting` as true to indicate that the builder function is invoked and loading but then `hasData` should be true.

```Dart
void main() {
  test('shouldRecreateState: true', () async {
    await RM.storageInitializerMock();
    Injected<int?> injected = RM.injectStream(
      () => Stream.fromFuture(
          Future.delayed(Duration(milliseconds: 100), () => 1)),
      initialState: 0,
      persist: () => PersistState(
        shouldRecreateTheState: true,
        key: 'injected',
        fromJson: int.parse,
        toJson: (s) => s.toString(),
      ),
    );
    // first initialization -> store value as persitant state
    expect(injected.state, equals(0));
    await Future.delayed(Duration(milliseconds: 200));
    expect(injected.state, equals(1));
    injected.setState((_) => 2);

    // re-initializing the state. the last stores value has been 2.
    // therefore, expect value 2
    injected.dispose();
    expect(injected.state, equals(2));
    // the state has a value, therefore (I) would not expect it to have data
    expect(injected.hasData, isTrue);
    await Future.delayed(Duration(milliseconds: 200));
    // re-invoke the builder function which returns 1 after 100 milliseconds
    expect(injected.state, equals(1));
  });
}
```

**Comment by GIfatahTH** [comment] 2021-06-29 11:33
@samuelstroschein 
Thank you again for your contribution. The issue is fixed as you requested, Please try it and feed me back.

**Comment by GIfatahTH** [comment] 2021-06-29 11:37
@samuelstroschein 
>And big sorry that I just saw you already implemented the proposal and merged it because why did you choose shouldRecreateTheState as callback? I find it a bit ambiguous since "the state" could refer to the persistent state or the state as created by the creator function. Something like shouldReinvokeCreatorFunction would have been less ambiguous.

Yes, you are right, shouldReinvokeCreatorFunction is better.

**Closed** 2021-09-11 11:33 UTC
