### ISSUE TITLE
Unexpected behavior (?) of the watch parameter

### ISSUE THREAD

**Issue by ResoDev** [GIfatahTH/states_rebuilder#37] opened 2020-01-09 18:46 UTC
Hello there! I'm really happy that this package is gaining some traction, especially on pub.dev

I don't understand why specifying a `watch` function on a `StateBuilder` like this
```dart
StateBuilder<AuthStore>(
  models: [Injector.getAsReactive<AuthStore>()],
  watch: (reactiveModel) => reactiveModel.state.canSignInWithApple,
  ...
```

prevents the callbacks on `setState` from running. This means I don't see any "flushbars" a.k.a. custom SnackBars displayed on the screen.

```dart
void signInWith(AuthProvider provider) {
  final authStoreReactiveModel = Injector.getAsReactive<AuthStore>();
  authStoreReactiveModel.setState(
    (s) => s.signInWithProvider(provider),
    onError: (context, failure) {
      if (failure is AuthFailure) {
        print('RUNNING');
        failure.iswitch(
          cancelledByUser: () =>
              FlushbarHelper.createInformation(message: 'Sign in cancelled')
                  .show(context),
          serverError: () =>
              FlushbarHelper.createError(message: 'Server error')
                  .show(context),
        );
      }
      throw failure;
    },
    onRebuildState: (context) {
      if (authStoreReactiveModel.hasData) {
        final message = authStoreReactiveModel.state.signedInUser.fold(
          () => 'Not Signed In',
          (user) => 'Signed In: ${user.name}',
        );
        FlushbarHelper.createSuccess(message: message).show(context);
      }
    },
  );
}
```

As soon as I remove the `watch` parameter from the `StateBuilder` everything works as it should.

**Comment by GIfatahTH** [comment] 2020-01-10 07:55
Thank you for your interest in this package. Yes, the package is starting to gain popularity after your tutorial.

For the reasons I indicated in # 33, the watch parameter works by taking a string snapshot before and after the state change and checking if they are different to notify observers. (This is an experimental feature).

The watch parameters works with primitive and (list, set and map in the next version).

For class instances, this will not work because `object.toString ()` (before) is equal to `object.toString ()` (after).

To make it work for objects you have to override `toString` to return a unique identification of the object.

The question ; what is the type of `canSignInWithApple`?

BTW, Why you are using `onRebuildState` instead of `onData` parameter?

**Comment by ResoDev** [comment] 2020-01-10 14:58
`canSignInWithApple` is just a `bool`.

I was using `onData` at first but then changed it to `onRebuildState` because wanted to make sure to test everything possible before opening an issue 😉

**Comment by GIfatahTH** [comment] 2020-01-10 16:35
For bool, it should work. Can you confirm that `canSignInWithApple ` changes?
```dart
StateBuilder<AuthStore>(
  models: [Injector.getAsReactive<AuthStore>()],
  watch: (reactiveModel) {
   print(reactiveModel.state.canSignInWithApple);
   return reactiveModel.state.canSignInWithApple;
  ...
```

I try it with this code and it works as expected.

```dart
//global varaible
bool _boolSwitcher = true;
StateBuilder<AuthStore>(
  models: [Injector.getAsReactive<AuthStore>()],
  watch: (reactiveModel) {
        print(_boolSwitcher);
         _boolSwitcher = !_boolSwitcher; // if this line is commented the widget will not rebuild.
        return _boolSwitcher;
}
  ...
```
If you comment the   _boolSwitcher = !_boolSwitcher; it will not rebuild.

**Comment by GIfatahTH** [comment] 2020-01-10 18:12
Oh, I got it. What happens to you is the expected behavior, think with me:
You are watching `canSignInWithApple` and observer will not rebuild unless the value of `canSignInWithApple` changes.
At the same time, you are calling `setState` with an asynchronous method (`s.signInWithProvider(provider)`). `States_rebuilder` will change the connectionState to awaiting and notify the observer, AND HERE the observer will not rebuild because it is watching `canSignInWithApple` that has not changed.

In the next version, I should set it to throw if using `watch` with asynchronous tasks.
OR, I should cache the last connectionState and compare it with the new connectionState and trigger notification if they are different and your code will work.

**Comment by ResoDev** [comment] 2020-01-10 19:22
Does this mean that the callbacks inside `ReactiveModel.setState()` are connected to the `StateBuilder` in some way? Because only the `StateBuilder` has the watch parameter specified but still, callbacks such as `onError` don't run inside `setState`.

**Comment by GIfatahTH** [comment] 2020-01-10 19:47
There is no connection between `ReactiveModel.setState` and `StateBuilder` other than that between the observable and observer in the context of the observer pattern.
I fixed the issue of using watch parameter with an asynchronous task, I will push it in the next version.
Until then If you want your code to work just add the connectionState to the watch return:
```dart
StateBuilder<AuthStore>(
  models: [Injector.getAsReactive<AuthStore>()],
  watch: (reactiveModel) {

   return '${reactiveModel.state.canSignInWithApple}${reactiveModel.connectionState}';
  ...
```
and it will work.

**Comment by akarabach** [comment] 2020-01-24 20:09
I can confirm that in V1.11.2 it work as I expected 👍

**Comment by akarabach** [comment] 2020-01-24 21:00
If value has not changed in set state and watch is defined for `StateBuilder`, waiting stuck, and I don't expect this. 


```
StateBuilder<AuthenticationService>(
              models: [Injector.getAsReactive<AuthenticationService>()],
              initState: (context, authenticationServiceRM) {
                authenticationServiceRM
                    .setState((state) => state.initService(context)); // lets image that value here has not changed
              },
              watch: (service) => service.state.authenticated,
              builder: (context, service) {
                if (service.isWaiting) { // always true if value has not changed in set state
                  return DefaultPage(
                    child: SplashScreen(),
                  );
                }
                if (!service.state.authenticated) {
                  return LoginPage();
                }
                return Home();
              }),
```

**Comment by akarabach** [comment] 2020-01-24 21:49
So, I just played around with this `'${reactiveModel.state.canSignInWithApple}${reactiveModel.connectionState}'` and I think that it is wrong.

It looks like `reactiveModel.connectionState` changes for every state change, and if property `reactiveModel.state.canSignInWithApple` in our case has not changed but another one changed (we call setState in another place) it triggers rerender

**Comment by GIfatahTH** [comment] 2020-02-04 20:13
@akarabach Sorry for my late response. I was occupied by rewriting the code from the ground using Test Driven Design principles and  I was amazed by the result I get.

> So, I just played around with this '${reactiveModel.state.canSignInWithApple}${reactiveModel.connectionState}' and I think that it is wrong.

you are right. If `setState` from another widget is called and if the called method is asynchronous, the `connectionState` will change from `waiting` to `hasData` (or `hasError`) and the supposedly watched widget will rerender even though the watched parameter is not changed. And I think this is not the wanted behavior.

In the 1.12.1 update, the watched widget will not rebuild unless the `connectionState` is in `hasData` status and the watched parameter changes. 
for example: 
```dart
StateBuilder<AuthStore>(
  models: [Injector.getAsReactive<AuthStore>()],
  watch: (reactiveModel) {

   return reactiveModel.state.canSignInWithApple;
  ...
```

This will not rebuild unless the `reactiveModel.hasData` is true and `canSignInWithApple changes`.

BUT what if I want the above widget to rebuild if the `canSignInWithApple` changes and if the `connectionState` changes ONLY if called from this widget. That is I want to prevent other widgets from changing the `connectionState` of this widget?!

I will illustrate comparing the ChangeNotifier case. Imagine this model class
```dart
class Model extends ChangeNotifier {
  bool canSignWithApple;
  String canSignWithAppleError;
  bool isCanSignWithAppleWaiting;

  void checkCanSignWithApple() async {
    canSignWithApple = false;
    isCanSignWithAppleWaiting= true
    notifyListeners();
    try {
      canSignWithApple = await appleLibrary();
     isCanSignWithAppleWaiting=false
      notifyListeners();
    } catch (e) {
      canSignWithAppleError = e.message;
     isCanSignWithAppleWaiting=false;
      notifyListeners();
    }
  }

  void anotherAsyncMethod()async{
    //before setup
    notifyListeners();
    try {
      //awaiting of a external async method
      //after has data setup
      notifyListeners();
    } catch (e) {
      //after has error setup
      notifyListeners();
    }
  }
}
```
In the UI you can consume this model and watch for changes of `canSignWithAppleError`  and `isCanSignWithAppleWaiting` and rebuild your widget if any of them changes. When the `anotherAsyncMethod` is called it will not affect the watched widget because the latter method will not change any of `canSignWithAppleError  or `isCanSignWithAppleWaiting`.

In the `states_rebuilder` world, you get rid of all the boilerplate and your model is simply:
```dart
class Model{
  bool canSignWithApple;

  void checkCanSignWithApple() async {
    canSignWithApple = await appleLibrary();
  }

  void anotherAsyncMethod() async {
    //awaiting of a external async method
  }
}
```
In the UI you can easily watch `canSignWithApple` and the `connectionState`. BUT when `anotherAsyncMethod` is called it will change `connectionState` and hence rebuild the watched method. Is this the price you have to pay to avoid boilerplate code?!! with states_rebuilder no
In `states_rebuilder` you can use tags to filter the rebuild notification and if `anotherAsyncMethod` is invoked with a specific tag, only widgets registered with that tag will rebuild.

Even a better approach add from 1.12.0 version is to use the concept of new reactive models with seeds. 

in the above example if I change `Injector.getAsReactive<AuthStore>()` to `Injector.getAsReactive<AuthStore>().asNew('mySeed')`

```dart
StateBuilder<AuthStore>(
  models: [Injector.getAsReactive<AuthStore>().asNew('mySeed')],
  watch: (reactiveModel) {

   return [ reactiveModel.state.canSignInWithApple, reactiveModel.connectionState];
  ...
```
What happens here is that I isolated this `StateBuilder` widget from other widgets by registering it to a new reactive model that wraps the same instance of `AuthStore`. And unless notifications are emitted from this new reactive model, the widget will not rebuild. Here you can even remove the `watch` parameter because it is not needed as this `StateBuilder` has its own reactive model that will not be affected by other reactive models.

I use the term seed here the in same way it is used in random number generator, That is if the widget is rebuilt it will get the same reactive model instance just like in random number generator you get the same sequence of random numbers.

Here is a snippet of code from the example of [firebase sign in](https://github.com/GIfatahTH/states-rebuilder-examples/blob/master/008-clean_architecture_firebase_login/lib/main.dart) :

```dart
class MyApp extends StatelessWidget {
  final userServiceRM = Injector.getAsReactive<UserService>();
  final appleCheckerRM = Injector.getAsReactive<AppSignInCheckerService>();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WhenRebuilder<UserService>(
       //register to new userServiceRM reactive model
        models: [userServiceRM.asNew('main_widget'), appleCheckerRM],
        initState: (_, userServiceRM) {
          // the exposed userServiceRM is the same new reactive model wiht seed 'main_widget'
          appleCheckerRM.setState((s) => s.check());
          userServiceRM.setState((s) => s.currentUser());
        },
        onWaiting: () => SplashScreen(),
        onError: (error) => Text(error.toString()),
        onData: (_) {
          return StateBuilder(
            // register to the singleton reactive model of userServiceRM
            models: [userServiceRM],
            builder: (_, __) {
              return userServiceRM.state.user == null
                  ? SignInPage()
                  : HomePage();
            },
          );
        },
      ),
    );
  }
}
```
`WhenRebuilder` is new widget add from version 1.12.0 is is similar to combining `StateBuilder` with `whenConnectionState`. It has another avantage. It exposes a combined state from the provided reactive models in the `models` list so that `onData` callback will not be called unless both models have data. (see docs for more information).

The point here is that `WhenRebuilder` is subscribed to a new reactive model with 'main_widget' as seed and the last `StateBuilder` is registered to the singleton reactive model. As a consequence, `WhenRebuilder ` is isolated from any unwanted rebuild from other widgets and `StateBuilder` can be rebuilt from other widgets in other pages and this is what we want.

**Comment by akarabach** [comment] 2020-02-06 19:27
> What happens here is that I isolated this `StateBuilder` widget from other widgets by registering it to a new reactive model that wraps the same instance of `AuthStore`. And unless notifications are emitted from this new reactive model, the widget will not rebuild. Here you can even remove the `watch` parameter because it is not needed as this `StateBuilder` has its own reactive model that will not be affected by other reactive models.

Does it mean that `this new reactive model` have the same state since `wraps the same instance of `AuthStore`` ?

**Comment by GIfatahTH** [comment] 2020-02-06 20:47
Yes, new reactive models have the same state. By the same state, I mean the same instance of the row model `AuthStore` in our case. 
```dart
authStoreRM.state == authStoreRM.asNew('seed1').state // is true
```
here `AuthStoreRM` means the reactive model of AuthStore.

BUT each reactive model will have its own status (idle, waiting, hasData, hasError, and error).

```dart
authStoreRM.isWaiting == authStoreRM.asNew('seend1').isWaiting // is false
```
AND, notification is bounded to the reactive model emiting it. If reactive model instance A emits a notification, other reactive model will not be affected.

```dart
authStoreRM.setState((s)=> ....) // will only notify widget subscribed to this AuthStoreRM 

authStoreRM.asNew('seed1').setState((s)=> ....)  // will only notify widget subscribed to this authStoreRM 
```
Notice that seed parameter in asNew is of dynamic type so that it can be enums
```dart
authStoreRM.asNew(SeedEnum.seed1)
```

In ChangeNotifier or futter_bloc, if you navigate to a new page and notify (add events to) the bloc, page in the stack will be notified and the build method will be invoked although they are invisible. 
With states_rebuilder by simply appending the reactive model by `asNew` you limit the rebuild to the visible view.

```dart
//In the new page
final authStoreRM = Injector.getAsReactive<AuthStore>().asNew('new page');

// Now authStoreRM  hold the new reactive instance
```

WHAT if I use this `asNew(SeedEnum.body)`  technique, and I am in a body widget, and I want to rebuild this body widget and a Text widget in the `appBar` that has been created using another reactive model instance  `asNew(SeedEnum.appBar)`? In other words, is it possible to notify other new reactive instances from a reactive instance? YES

In the body widget when calling setState, you have the ability to notify widgets registered to other reactive instances.
```dart
bodyReactiveModel.setState((s)=> mehtod(),
 seeds: [SeedEnum.appBar],
)
```
With the concept of tags, watch, asNew and the seeds parameter in setState you have the full control upon which widgets you want to be notified and when to notify it.

**Comment by akarabach** [comment] 2020-02-07 08:11
> In ChangeNotifier or futter_bloc, if you navigate to a new page and notify (add events to) the bloc, page in the stack will be notified and the build method will be invoked although they are invisible.
> With states_rebuilder by simply appending the reactive model by `asNew` you limit the rebuild to the visible view.

It's amazing. Great work 👍

**Closed** 2020-03-20 14:43 UTC
